// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'a71ce4e43551f3b9157d41fa3bd6a64401e1a587fe76c247ada5dc3a263240e1'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly MenuCard: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly itemName: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly itemPrice: CodecTypes['pg/float8@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly prepTimeMinutes: CodecTypes['pg/int4@1']['output'];
      readonly avgRating: CodecTypes['pg/float8@1']['output'];
      readonly reviewCount: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Offer: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly discountPercent: CodecTypes['pg/float8@1']['output'];
      readonly validFrom: CodecTypes['pg/date-string@1']['output'];
      readonly validTo: CodecTypes['pg/date-string@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
    };
    readonly Rating: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly menuCardId: CodecTypes['pg/int4@1']['output'];
      readonly reservationId: CodecTypes['pg/int4@1']['output'] | null;
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly comment: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Reservation: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly tableId: CodecTypes['pg/int4@1']['output'];
      readonly partySize: CodecTypes['pg/int4@1']['output'];
      readonly bookingTime: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Restaurant: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'];
      readonly cuisineType: CodecTypes['pg/text@1']['output'];
      readonly openingHours: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly RestaurantAddress: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly line1: CodecTypes['pg/text@1']['output'];
      readonly line2: CodecTypes['pg/text@1']['output'] | null;
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly state: CodecTypes['pg/text@1']['output'];
      readonly pincode: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'];
      readonly lng: CodecTypes['pg/float8@1']['output'];
    };
    readonly RestaurantTable: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly tableNumber: CodecTypes['pg/text@1']['output'];
      readonly capacity: CodecTypes['pg/int4@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly auth0Id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly profileComplete: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly UserAddress: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly line1: CodecTypes['pg/text@1']['output'];
      readonly line2: CodecTypes['pg/text@1']['output'] | null;
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly state: CodecTypes['pg/text@1']['output'];
      readonly pincode: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'];
      readonly lng: CodecTypes['pg/float8@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly MenuCard: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly itemName: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly itemPrice: CodecTypes['pg/float8@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly prepTimeMinutes: CodecTypes['pg/int4@1']['input'];
      readonly avgRating: CodecTypes['pg/float8@1']['input'];
      readonly reviewCount: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Offer: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly discountPercent: CodecTypes['pg/float8@1']['input'];
      readonly validFrom: CodecTypes['pg/date-string@1']['input'];
      readonly validTo: CodecTypes['pg/date-string@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
    };
    readonly Rating: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly menuCardId: CodecTypes['pg/int4@1']['input'];
      readonly reservationId: CodecTypes['pg/int4@1']['input'] | null;
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly comment: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Reservation: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly tableId: CodecTypes['pg/int4@1']['input'];
      readonly partySize: CodecTypes['pg/int4@1']['input'];
      readonly bookingTime: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Restaurant: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'];
      readonly cuisineType: CodecTypes['pg/text@1']['input'];
      readonly openingHours: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly RestaurantAddress: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly line1: CodecTypes['pg/text@1']['input'];
      readonly line2: CodecTypes['pg/text@1']['input'] | null;
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly state: CodecTypes['pg/text@1']['input'];
      readonly pincode: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'];
      readonly lng: CodecTypes['pg/float8@1']['input'];
    };
    readonly RestaurantTable: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly tableNumber: CodecTypes['pg/text@1']['input'];
      readonly capacity: CodecTypes['pg/int4@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly auth0Id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly profileComplete: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly UserAddress: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly line1: CodecTypes['pg/text@1']['input'];
      readonly line2: CodecTypes['pg/text@1']['input'] | null;
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly state: CodecTypes['pg/text@1']['input'];
      readonly pincode: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'];
      readonly lng: CodecTypes['pg/float8@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly menuCard: {
      readonly avgRating: CodecTypes['pg/float8@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly itemName: CodecTypes['pg/text@1']['output'];
      readonly itemPrice: CodecTypes['pg/float8@1']['output'];
      readonly prepTimeMinutes: CodecTypes['pg/int4@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly reviewCount: CodecTypes['pg/int4@1']['output'];
    };
    readonly offer: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly discountPercent: CodecTypes['pg/float8@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly validFrom: CodecTypes['pg/date-string@1']['output'];
      readonly validTo: CodecTypes['pg/date-string@1']['output'];
    };
    readonly rating: {
      readonly comment: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly menuCardId: CodecTypes['pg/int4@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly reservationId: CodecTypes['pg/int4@1']['output'] | null;
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly reservation: {
      readonly bookingTime: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly partySize: CodecTypes['pg/int4@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly tableId: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly restaurant: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly cuisineType: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly openingHours: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'];
    };
    readonly restaurantAddress: {
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'];
      readonly line1: CodecTypes['pg/text@1']['output'];
      readonly line2: CodecTypes['pg/text@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'];
      readonly pincode: CodecTypes['pg/text@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly state: CodecTypes['pg/text@1']['output'];
    };
    readonly restaurantTable: {
      readonly capacity: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly restaurantId: CodecTypes['pg/int4@1']['output'];
      readonly tableNumber: CodecTypes['pg/text@1']['output'];
    };
    readonly user: {
      readonly auth0Id: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly profileComplete: CodecTypes['pg/bool@1']['output'];
    };
    readonly userAddress: {
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'];
      readonly line1: CodecTypes['pg/text@1']['output'];
      readonly line2: CodecTypes['pg/text@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'];
      readonly pincode: CodecTypes['pg/text@1']['output'];
      readonly state: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly menuCard: {
      readonly avgRating: CodecTypes['pg/float8@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly itemName: CodecTypes['pg/text@1']['input'];
      readonly itemPrice: CodecTypes['pg/float8@1']['input'];
      readonly prepTimeMinutes: CodecTypes['pg/int4@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly reviewCount: CodecTypes['pg/int4@1']['input'];
    };
    readonly offer: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly discountPercent: CodecTypes['pg/float8@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly validFrom: CodecTypes['pg/date-string@1']['input'];
      readonly validTo: CodecTypes['pg/date-string@1']['input'];
    };
    readonly rating: {
      readonly comment: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly menuCardId: CodecTypes['pg/int4@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly reservationId: CodecTypes['pg/int4@1']['input'] | null;
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly reservation: {
      readonly bookingTime: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly partySize: CodecTypes['pg/int4@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly tableId: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly restaurant: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly cuisineType: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly openingHours: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'];
    };
    readonly restaurantAddress: {
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'];
      readonly line1: CodecTypes['pg/text@1']['input'];
      readonly line2: CodecTypes['pg/text@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'];
      readonly pincode: CodecTypes['pg/text@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly state: CodecTypes['pg/text@1']['input'];
    };
    readonly restaurantTable: {
      readonly capacity: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly restaurantId: CodecTypes['pg/int4@1']['input'];
      readonly tableNumber: CodecTypes['pg/text@1']['input'];
    };
    readonly user: {
      readonly auth0Id: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly profileComplete: CodecTypes['pg/bool@1']['input'];
    };
    readonly userAddress: {
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'];
      readonly line1: CodecTypes['pg/text@1']['input'];
      readonly line2: CodecTypes['pg/text@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'];
      readonly pincode: CodecTypes['pg/text@1']['input'];
      readonly state: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly menuCard: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly restaurantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly itemName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly itemPrice: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly imageUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly prepTimeMinutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly avgRating: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 0>;
                  };
                };
                readonly reviewCount: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'menuCard_restaurantId_idx_cf3ee7d0';
                  readonly prefix: 'menuCard_restaurantId_idx';
                  readonly columns: readonly ['restaurantId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'menuCard';
                    readonly columns: readonly ['restaurantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'restaurant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly offer: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly restaurantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly discountPercent: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly validFrom: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly validTo: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly isActive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'offer_restaurantId_idx_cf3ee7d0';
                  readonly prefix: 'offer_restaurantId_idx';
                  readonly columns: readonly ['restaurantId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'offer';
                    readonly columns: readonly ['restaurantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'restaurant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly rating: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly menuCardId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly reservationId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly rating: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly comment: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'rating_userId_idx_a489d58a';
                  readonly prefix: 'rating_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'rating_menuCardId_idx_9eea6efd';
                  readonly prefix: 'rating_menuCardId_idx';
                  readonly columns: readonly ['menuCardId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'rating_reservationId_idx_868923bb';
                  readonly prefix: 'rating_reservationId_idx';
                  readonly columns: readonly ['reservationId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rating';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rating';
                    readonly columns: readonly ['menuCardId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'menuCard';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rating';
                    readonly columns: readonly ['reservationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reservation';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly reservation: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly restaurantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tableId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly partySize: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly bookingTime: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'reservation_userId_idx_a489d58a';
                  readonly prefix: 'reservation_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'reservation_restaurantId_idx_cf3ee7d0';
                  readonly prefix: 'reservation_restaurantId_idx';
                  readonly columns: readonly ['restaurantId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'reservation_tableId_idx_f5c39e5c';
                  readonly prefix: 'reservation_tableId_idx';
                  readonly columns: readonly ['tableId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reservation';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reservation';
                    readonly columns: readonly ['restaurantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'restaurant';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reservation';
                    readonly columns: readonly ['tableId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'restaurantTable';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly restaurant: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cuisineType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly openingHours: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly restaurantAddress: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly restaurantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly line1: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly line2: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly state: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pincode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly lng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['restaurantId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'restaurantAddress';
                    readonly columns: readonly ['restaurantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'restaurant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly restaurantTable: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly restaurantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tableNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly capacity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly isActive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'restaurantTable_restaurantId_idx_cf3ee7d0';
                  readonly prefix: 'restaurantTable_restaurantId_idx';
                  readonly columns: readonly ['restaurantId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'restaurantTable';
                    readonly columns: readonly ['restaurantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'restaurant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly auth0Id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly profileComplete: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly userAddress: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly line1: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly line2: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly state: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pincode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly lng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'userAddress_userId_idx_a489d58a';
                  readonly prefix: 'userAddress_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'userAddress';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly userAddress: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UserAddress';
    };
    readonly restaurant: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Restaurant';
    };
    readonly restaurantAddress: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RestaurantAddress';
    };
    readonly menuCard: { readonly namespace: 'public' & NamespaceId; readonly model: 'MenuCard' };
    readonly restaurantTable: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RestaurantTable';
    };
    readonly offer: { readonly namespace: 'public' & NamespaceId; readonly model: 'Offer' };
    readonly reservation: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Reservation';
    };
    readonly rating: { readonly namespace: 'public' & NamespaceId; readonly model: 'Rating' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly MenuCard: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly restaurantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly itemName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly itemPrice: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly prepTimeMinutes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly avgRating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly reviewCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly ratings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Rating';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['menuCardId'];
                };
              };
              readonly restaurant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Restaurant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['restaurantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'menuCard';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly restaurantId: { readonly column: 'restaurantId' };
                readonly itemName: { readonly column: 'itemName' };
                readonly description: { readonly column: 'description' };
                readonly itemPrice: { readonly column: 'itemPrice' };
                readonly category: { readonly column: 'category' };
                readonly imageUrl: { readonly column: 'imageUrl' };
                readonly prepTimeMinutes: { readonly column: 'prepTimeMinutes' };
                readonly avgRating: { readonly column: 'avgRating' };
                readonly reviewCount: { readonly column: 'reviewCount' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Offer: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly restaurantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly discountPercent: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly validFrom: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly validTo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly restaurant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Restaurant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['restaurantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'offer';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly restaurantId: { readonly column: 'restaurantId' };
                readonly title: { readonly column: 'title' };
                readonly description: { readonly column: 'description' };
                readonly discountPercent: { readonly column: 'discountPercent' };
                readonly validFrom: { readonly column: 'validFrom' };
                readonly validTo: { readonly column: 'validTo' };
                readonly isActive: { readonly column: 'isActive' };
              };
            };
          };
          readonly Rating: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly menuCardId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly reservationId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly comment: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly menuCard: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MenuCard';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['menuCardId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly reservation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reservation';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['reservationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'rating';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly menuCardId: { readonly column: 'menuCardId' };
                readonly reservationId: { readonly column: 'reservationId' };
                readonly rating: { readonly column: 'rating' };
                readonly comment: { readonly column: 'comment' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Reservation: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly restaurantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tableId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly partySize: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly bookingTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly ratings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Rating';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['reservationId'];
                };
              };
              readonly restaurant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Restaurant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['restaurantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly table: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RestaurantTable';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tableId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'reservation';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly restaurantId: { readonly column: 'restaurantId' };
                readonly tableId: { readonly column: 'tableId' };
                readonly partySize: { readonly column: 'partySize' };
                readonly bookingTime: { readonly column: 'bookingTime' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Restaurant: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cuisineType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly openingHours: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly address: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RestaurantAddress';
                };
                readonly cardinality: '1:1';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['restaurantId'];
                };
              };
              readonly menuCards: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MenuCard';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['restaurantId'];
                };
              };
              readonly offers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Offer';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['restaurantId'];
                };
              };
              readonly reservations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reservation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['restaurantId'];
                };
              };
              readonly tables: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RestaurantTable';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['restaurantId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'restaurant';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly description: { readonly column: 'description' };
                readonly phone: { readonly column: 'phone' };
                readonly cuisineType: { readonly column: 'cuisineType' };
                readonly openingHours: { readonly column: 'openingHours' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly RestaurantAddress: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly restaurantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly line1: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly line2: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly state: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pincode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lat: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly lng: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
            };
            readonly relations: {
              readonly restaurant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Restaurant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['restaurantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'restaurantAddress';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly restaurantId: { readonly column: 'restaurantId' };
                readonly line1: { readonly column: 'line1' };
                readonly line2: { readonly column: 'line2' };
                readonly city: { readonly column: 'city' };
                readonly state: { readonly column: 'state' };
                readonly pincode: { readonly column: 'pincode' };
                readonly lat: { readonly column: 'lat' };
                readonly lng: { readonly column: 'lng' };
              };
            };
          };
          readonly RestaurantTable: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly restaurantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tableNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly capacity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly reservations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reservation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tableId'];
                };
              };
              readonly restaurant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Restaurant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['restaurantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'restaurantTable';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly restaurantId: { readonly column: 'restaurantId' };
                readonly tableNumber: { readonly column: 'tableNumber' };
                readonly capacity: { readonly column: 'capacity' };
                readonly isActive: { readonly column: 'isActive' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly auth0Id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly profileComplete: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly addresses: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserAddress';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly ratings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Rating';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly reservations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reservation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly auth0Id: { readonly column: 'auth0Id' };
                readonly name: { readonly column: 'name' };
                readonly email: { readonly column: 'email' };
                readonly phone: { readonly column: 'phone' };
                readonly profileComplete: { readonly column: 'profileComplete' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly UserAddress: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly line1: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly line2: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly state: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pincode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lat: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly lng: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'userAddress';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly line1: { readonly column: 'line1' };
                readonly line2: { readonly column: 'line2' };
                readonly city: { readonly column: 'city' };
                readonly state: { readonly column: 'state' };
                readonly pincode: { readonly column: 'pincode' };
                readonly lat: { readonly column: 'lat' };
                readonly lng: { readonly column: 'lng' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
